export const searchOptions = [
  { value: "TWOU", label: "2U INC" },
  { value: "TDCH", label: "30DC INC" },
  { value: "DPSM", label: "3D PIONEER SYSTEMS INC" },
  { value: "EGHT", label: "8X8 INC" },
  { value: "ATEN", label: "A10 NETWORKS INC" },
  { value: "ACIW", label: "ACI WORLDWIDE INC" },
  { value: "ACTA", label: "ACTUA CORP" },
  { value: "ADXA", label: "ADEXA INC" },
  { value: "ADBE", label: "ADOBE INC" },
  { value: "AVOI", label: "ADVANCED VOICE RECOGNITION" },
  { value: "ADVC", label: "ADVANT-E CORP" },
  { value: "ADGO", label: "ADVANTEGO CORP" },
  { value: "AGYS", label: "AGILYSYS INC" },
  { value: "ALRM", label: "ALARM.COM HOLDINGS INC" },
  { value: "ADGL", label: "ALLDIGITAL HOLDINGS INC" },
  { value: "ALTR", label: "ALTAIR ENGINEERING INC" },
  { value: "AYX", label: "ALTERYX INC" },
  { value: "ARSC", label: "AMERICAN SECURITY RES CORP" },
  { value: "AMSWA", label: "AMERICAN SOFTWARE -CL A" },
  { value: "PLAN", label: "ANAPLAN INC" },
  { value: "ANSS", label: "ANSYS INC" },
  { value: "APPF", label: "APPFOLIO INC" },
  { value: "APPN", label: "APPIAN CORP" },
  { value: "GDTI", label: "APPLIED VISUAL SCIENCES INC" },
  { value: "APTY", label: "APT SYSTEMS INC" },
  { value: "ASAN", label: "ASANA INC" },
  { value: "AZPN", label: "ASPEN TECHNOLOGY INC" },
  { value: "ASUR", label: "ASURE SOFTWARE INC" },
  { value: "AEYE", label: "AUDIOEYE INC" },
  { value: "ADSK", label: "AUTODESK INC" },
  { value: "ADP", label: "AUTOMATIC DATA PROCESSING" },
  { value: "AVLR", label: "AVALARA INC" },
  { value: "AVYA", label: "AVAYA HLDGS CORP" },
  { value: "AWRE", label: "AWARE INC" },
  { value: "CUDA", label: "BARRACUDA NETWORKS INC" },
  { value: "BNFT", label: "BENEFITFOCUS INC" },
  { value: "BSY", label: "BENTLEY SYSTEMS INC" },
  { value: "BIGC", label: "BIGCOMMERCE HOLDIN INC" },
  { value: "BILL", label: "BILL.COM HOLDINGS INC" },
  { value: "BKYI", label: "BIO-KEY INTERNATIONAL INC" },
  { value: "BBOX", label: "BLACK BOX CORP" },
  { value: "BLKB", label: "BLACKBAUD INC" },
  { value: "BLBX", label: "BLACKBOXSTOCKS INC" },
  { value: "BL", label: "BLACKLINE INC" },
  { value: "BCDS", label: "BLAQCLOUDS INC" },
  { value: "EPAY", label: "BOTTOMLINE TECHNOLOGIES INC" },
  { value: "BOX", label: "BOX INC" },
  { value: "BOXL", label: "BOXLIGHT CORP" },
  { value: "ECRY", label: "BRAVATEK SOLUTIONS INC" },
  { value: "BLIN", label: "BRIDGELINE DIGITAL INC" },
  { value: "BDGY", label: "BRIDGEWAY NATIONAL CORP" },
  { value: "SCDA", label: "B-SCADA INC" },
  { value: "BSQR", label: "BSQUARE CORP" },
  { value: "BUSY", label: "BUSYBOX.COM INC" },
  { value: "CDNS", label: "CADENCE DESIGN SYSTEMS INC" },
  { value: "CDK", label: "CDK GLOBAL INC" },
  { value: "CRNC", label: "CERENCE INC" },
  { value: "FLT", label: "CERIDIAN CORP" },
  { value: "CDAY", label: "CERIDIAN HCM HOLDING" },
  { value: "CSJT", label: "CHANGSHENG INTERNATIONAL GRO" },
  { value: "ECOM", label: "CHANNELADVISOR CORP" },
  { value: "MSHF", label: "CHINA YANYUN YHU NTL ED GRP" },
  { value: "CICN", label: "CICERO INC" },
  { value: "CMXX", label: "CIMETRIX INC" },
  { value: "CLOK", label: "CIPHERLOC CORP" },
  { value: "CTXS", label: "CITRIX SYSTEMS INC" },
  { value: "CLSK", label: "CLEANSPARK INC" },
  { value: "CLIS", label: "CLICKSTREAM CORP" },
  { value: "CATI", label: "CLONE ALGO TECHNOLOGIES INC" },
  { value: "CLDR", label: "CLOUDERA INC" },
  { value: "NET", label: "CLOUDFLARE INC" },
  { value: "CDRBQ", label: "CODE REBEL CORP" },
  { value: "CGUD", label: "COM GUARD.COM INC" },
  { value: "CVLT", label: "COMMVAULT SYSTEMS INC" },
  { value: "CSOD", label: "CORNERSTONE ONDEMAND INC" },
  { value: "COUP", label: "COUPA SOFTWARE INC" },
  { value: "CRWD", label: "CROWDSTRIKE HOLDINGS INC" },
  { value: "CYBF", label: "CYBERFORT SOFTWARE INC" },
  { value: "CYRN", label: "CYREN LTD" },
  { value: "DDOG", label: "DATADOG INC" },
  { value: "MSP", label: "DATTO HOLDING CORP" },
  { value: "DLAD", label: "DEALERADVANCE INC" },
  { value: "DGLT", label: "DIGILITI MONEY GROUP INC" },
  { value: "DMRC", label: "DIGIMARC CORP" },
  { value: "APPS", label: "DIGITAL TURBINE INC" },
  { value: "DOCU", label: "DOCUSIGN INC" },
  { value: "DOMO", label: "DOMO INC" },
  { value: "DBX", label: "DROPBOX INC" },
  { value: "DCT", label: "DUCK CREEK TECHNOL INC" },
  { value: "DT", label: "DYNATRACE INC" },
  { value: "EOPN", label: "E2OPEN INC" },
  { value: "EBIX", label: "EBIX INC" },
  { value: "ZEST", label: "ECOARK HOLDINGS INC" },
  { value: "EGAN", label: "EGAIN CORP" },
  { value: "ESTC", label: "ELASTIC NV" },
  { value: "ELCO", label: "ELCOM INTERNATIONAL INC" },
  { value: "EINF", label: "ENTERPRISE INFORMATICS INC" },
  { value: "ENV", label: "ENVESTNET INC" },
  { value: "EVBG", label: "EVERBRIDGE INC" },
  { value: "EVOL", label: "EVOLVING SYSTEMS INC" },
  { value: "EZEN", label: "EZENIA INC" },
  { value: "FICO", label: "FAIR ISAAC CORP" },
  { value: "FALC", label: "FALCONSTOR SOFTWARE INC" },
  { value: "FASDF", label: "FANTASY ACES DAILY FANTASY" },
  { value: "FSLY", label: "FASTLY INC" },
  { value: "MNDT", label: "FIREEYE INC" },
  { value: "FIVN", label: "FIVE9 INC" },
  { value: "FTNT", label: "FORTINET INC" },
  { value: "FFN", label: "FRIENDFINDER NETWORKS INC" },
  { value: "GMPW", label: "GIVEMEPOWER CORP" },
  { value: "GPCMQ", label: "GRANDPARENTS.COM INC" },
  { value: "GPDB", label: "GREEN POLKADOT BOX INC" },
  { value: "GVP", label: "GSE SYSTEMS INC" },
  { value: "GTYH", label: "GTY TECHNOLOGY HOLDINGS" },
  { value: "GWRE", label: "GUIDEWIRE SOFTWARE INC" },
  { value: "HPTO", label: "HOPTO INC" },
  { value: "WSTM", label: "HRSOFT INC" },
  { value: "HUBS", label: "HUBSPOT INC" },
  { value: "IGII", label: "IBSG INTERNATIONAL INC" },
  { value: "IDEX", label: "IDEANOMICS INC" },
  { value: "IWSY", label: "IMAGEWARE SYSTEMS INC" },
  { value: "IRIC", label: "INFORMATION RESOURCES INC" },
  { value: "IBSS", label: "INTEGRATED BUSINESS SYS &SVC" },
  { value: "CCRD", label: "INTELLIGENT SYSTEM CORP" },
  { value: "INLX", label: "INTELLINETICS INC" },
  { value: "ITMSF", label: "INTERMAP TECHNOLOGIES CORP" },
  { value: "INTZ", label: "INTRUSION INC" },
  { value: "INTU", label: "INTUIT INC" },
  { value: "INUV", label: "INUVO INC" },
  { value: "IRNC", label: "IRONCLAD ENCRYPTION CORP" },
  { value: "ISIGN", label: "ISIGN SOLUTIONS INC" },
  { value: "RTME", label: "ISOCIALY INC" },
  { value: "ISDR", label: "ISSUER DIRECT CORP" },
  { value: "IVDA", label: "IVEDA SOLUTIONS INC" },
  { value: "ZD", label: "J2 GLOBAL INC" },
  { value: "JACK", label: "JACK IN THE BOX INC" },
  { value: "JAMF", label: "JAMF HOLDING CORP" },
  { value: "JDAS", label: "JDA SOFTWARE GROUP INC" },
  { value: "FROG", label: "JFROG LTD" },
  { value: "MAGY", label: "KIWIBOX COM INC" },
  { value: "KRON", label: "KRONOS INC" },
  { value: "LWSN", label: "LAWSON SOFTWARE INC" },
  { value: "LVBX", label: "LEVELBLOX INC" },
  { value: "LIQB", label: "LIQUI-BOX CORP" },
  { value: "LIQD", label: "LIQUID HOLDINGS GROUP INC" },
  { value: "LMSC", label: "LIVE MICROSYSTEMS INC" },
  { value: "LPSN", label: "LIVEPERSON INC" },
  { value: "MANH", label: "MANHATTAN ASSOCIATES INC" },
  { value: "MRIN", label: "MARIN SOFTWARE INC" },
  { value: "MAXD", label: "MAX SOUND CORP" },
  { value: "MDLA", label: "MEDALLIA INC" },
  { value: "MEDT", label: "MEDIATECHNICS CORP" },
  { value: "MGTI", label: "MGT CAPITAL INVESTMENTS INC" },
  { value: "MSFT", label: "MICROSOFT CORP" },
  { value: "MSTR", label: "MICROSTRATEGY INC" },
  { value: "MITK", label: "MITEK SYSTEMS INC" },
  { value: "MIXT", label: "MIX TELEMATICS LTD" },
  { value: "MOBL", label: "MOBILEIRON INC" },
  { value: "MODN", label: "MODEL N INC" },
  { value: "MDB", label: "MONGODB INC" },
  { value: "APPZ", label: "MONSTER ARTS" },
  { value: "NCNO", label: "NCINO INC" },
  { value: "NEOM", label: "NEOMEDIA TECHNOLOGIES INC" },
  { value: "NTWK", label: "NETSOL TECHNOLOGIES INC" },
  { value: "NEWR", label: "NEW RELIC INC" },
  { value: "NLOK", label: "NORTONLIFELOCK INC" },
  { value: "NTFY", label: "NOTIFY TECHNOLOGY CORP" },
  { value: "NUAN", label: "NUANCE COMMUNICATIONS INC" },
  { value: "NTNX", label: "NUTANIX INC" },
  { value: "OBLG", label: "OBLONG INC" },
  { value: "OKTA", label: "OKTA INC" },
  { value: "OMTL", label: "OMTOOL LTD" },
  { value: "OSPN", label: "ONESPAN INC" },
  { value: "ORCL", label: "ORACLE CORP" },
  { value: "PD", label: "PAGERDUTY INC" },
  { value: "PAYD", label: "PAID INC" },
  { value: "PLTR", label: "PALANTIR TECHNOLOG INC" },
  { value: "PANW", label: "PALO ALTO NETWORKS INC" },
  { value: "TEUM", label: "PARETEUM CORP" },
  { value: "PCYG", label: "PARK CITY GROUP INC" },
  { value: "DIRI", label: "PAYBOX CORP" },
  { value: "PAYX", label: "PAYCHEX INC" },
  { value: "PAYC", label: "PAYCOM SOFTWARE INC" },
  { value: "PCTY", label: "PAYLOCITY HOLDING CORP" },
  { value: "PEGA", label: "PEGASYSTEMS INC" },
  { value: "PHUN", label: "PHUNWARE INC" },
  { value: "PING", label: "PING IDENTITY HOLDING CORP" },
  { value: "PS", label: "PLURALSIGHT INC" },
  { value: "PSOL", label: "PRIMAL SOLUTIONS INC" },
  { value: "PRGS", label: "PROGRESS SOFTWARE CORP" },
  { value: "PFPT", label: "PROOFPOINT INC" },
  { value: "PRO", label: "PROS HOLDINGS INC" },
  { value: "PTC", label: "PTC INC" },
  { value: "PLFX", label: "PULSE EVOLUTION CORP" },
  { value: "QTWO", label: "Q2 HOLDINGS INC" },
  { value: "QADI", label: "QAD INC" },
  { value: "QLYS", label: "QUALYS INC" },
  { value: "LOTI", label: "QUANTGATE SYSTEMS INC" },
  { value: "QUMU", label: "QUMU CORP" },
  { value: "RDAR", label: "RAADR INC" },
  { value: "RWWI", label: "RAND WORLDWIDE INC" },
  { value: "RPD", label: "RAPID7 INC" },
  { value: "RNWK", label: "REALNETWORKS INC" },
  { value: "RP", label: "REALPAGE INC" },
  { value: "RIHT", label: "RIGHTSCORP INC" },
  { value: "RNG", label: "RINGCENTRAL INC" },
  { value: "RIOT", label: "RIOT BLOCKCHAIN INC" },
  { value: "RKFL", label: "ROCKETFUEL BLOCKCHAIN INC" },
  { value: "QPRJ", label: "RORINE INTL HOLDING CORP" },
  { value: "RST", label: "ROSETTA STONE INC" },
  { value: "SAIL", label: "SAILPOINT TECHNO HLDG" },
  { value: "CRM", label: "SALESFORCE.COM INC" },
  { value: "SCNTQ", label: "SCIENT INC" },
  { value: "SEAC", label: "SEACHANGE INTERNATIONAL INC" },
  { value: "SCWX", label: "SECUREWORKS CORP" },
  { value: "NOW", label: "SERVICENOW INC" },
  { value: "SHSP", label: "SHARPSPRING INC" },
  { value: "SSTI", label: "SHOTSPOTTER INC" },
  { value: "SMRL", label: "SIMTROL INC" },
  { value: "SITOQ", label: "SITO MOBILE LTD" },
  { value: "SKYB", label: "SKYBOX INTL INC" },
  { value: "WORK", label: "SLACK TECHNOLOGIES INC" },
  { value: "SMME", label: "SMARTMETRIC INC" },
  { value: "SMAR", label: "SMARTSHEET INC" },
  { value: "SMSI", label: "SMITH MICRO SOFTWARE INC" },
  { value: "SNOW", label: "SNOWFLAKE INC" },
  { value: "SOFT", label: "SOFTECH INC" },
  { value: "SWI", label: "SOLARWINDS CORP" },
  { value: "SOFO", label: "SONIC FOUNDRY INC" },
  { value: "SPLK", label: "SPLUNK INC" },
  { value: "SPT", label: "SPROUT SOCIAL INC" },
  { value: "SPSC", label: "SPS COMMERCE INC" },
  { value: "SSNC", label: "SS&C TECHNOLOGIES HLDGS INC" },
  { value: "SUMO", label: "SUMO LOGIC INC" },
  { value: "MNTV", label: "SVMK INC" },
  { value: "SYNC", label: "SYNACOR INC" },
  { value: "SNCR", label: "SYNCHRONOSS TECHNOLOGIES" },
  { value: "SNPS", label: "SYNOPSYS INC" },
  { value: "TTCM", label: "TAUTACHROME INC" },
  { value: "TNAV", label: "TELENAV INC" },
  { value: "TENB", label: "TENABLE HOLDINGS INC" },
  { value: "TDC", label: "TERADATA CORP" },
  { value: "TGLO", label: "THEGLOBE.COM INC" },
  { value: "TIBX", label: "TIBCO SOFTWARE INC" },
  { value: "TNTRQ", label: "TINTRI INC" },
  { value: "TMMI", label: "TMM INC" },
  { value: "TTD", label: "TRADE DESK INC" },
  { value: "TWLO", label: "TWILIO INC" },
  { value: "TYL", label: "TYLER TECHNOLOGIES INC" },
  { value: "ULTI", label: "ULTIMATE SOFTWARE GROUP INC" },
  { value: "UTRXB", label: "UNITRONIX CORP" },
  { value: "U", label: "UNITY SOFTWARE INC" },
  { value: "UPLD", label: "UPLAND SOFTWARE INC" },
  { value: "MSYL", label: "VANCORD CAPITAL INC" },
  { value: "VRNS", label: "VARONIS SYSTEMS INC" },
  { value: "QUGB", label: "VDO-PH INTERNATIONAL INC" },
  { value: "VEEV", label: "VEEVA SYSTEMS INC" },
  { value: "VERB", label: "VERB TECHNOLOGY CO INC" },
  { value: "VRNT", label: "VERINT SYSTEMS INC" },
  { value: "VERI", label: "VERITONE INC" },
  { value: "VERX", label: "VERTEX INC" },
  { value: "VCSY", label: "VERTICAL COMPUTER SYS INC" },
  { value: "VHC", label: "VIRNETX HOLDING CORP" },
  { value: "OTTV", label: "VIVA ENTERTAINMENT GROUP INC" },
  { value: "VMW", label: "VMWARE INC -CL A" },
  { value: "VYGVF", label: "VOYAGER DIGITAL LTD" },
  { value: "VBTC", label: "VUBOTICS INC" },
  { value: "WODI", label: "WOD RETAIL SOLUTIONS" },
  { value: "WDAY", label: "WORKDAY INC" },
  { value: "WK", label: "WORKIVA INC" },
  { value: "XCLL", label: "XCELMOBILITY INC" },
  { value: "XPER", label: "XPERI HOLDING CORP" },
  { value: "YPPN", label: "YAPPN CORP" },
  { value: "YEXT", label: "YEXT INC" },
  { value: "ZEN", label: "ZENDESK INC" },
  { value: "ZIXI", label: "ZIX CORP" },
  { value: "ZOOM", label: "ZOOM TELEPHONICS INC" },
  { value: "ZM", label: "ZOOM VIDEO COMUNICATIONS INC" },
  { value: "ZMWYF", label: "ZOOMAWAY TRAVEL INC" },
  { value: "ZI", label: "ZOOMINFO TECHNOLOGIES" },
  { value: "ZS", label: "ZSCALER INC" },
  { value: "ZUO", label: "ZUORA INC" }
];

export const timeseriesChartLabels = [
  { value: "ARR", label: "Annual Recurring Revenue (ARR)" },
  { value: "NRR", label: "Net Revenue Retention Rate (NRR)" },
  { value: "TCUS", label: "Total customers" },
  { value: "PP", label: "Payback Period (Months)" },
  { value: "ICAC", label: "Implied CAC" },
  { value: "ILTV", label: "Implied LTV (5 Years)" },
];

export const overviewDataLabels = [
    {
      value: "0",
      label: "Annual Recurring Revenue (ARR)",
      byLine: "For the latest quarter",
    },
    {
      value: "1",
      label: "Net Revenue Retention Rate (NRR)",
      byLine: "For the latest quarter",
    },
    {
      value: "2",
      label: "Total customers",
      byLine: "For the latest quarter",
    },
  ];
