export const searchOptions = [
    { value: '30DC INC', label: '30DC INC' },
    { value: '3D PIONEER SYSTEMS INC', label: '3D PIONEER SYSTEMS INC' },
    { value: '8X8 INC', label: '8X8 INC' },
    { value: 'A10 NETWORKS INC', label: 'A10 NETWORKS INC' },
    { value: 'ACI WORLDWIDE INC', label: 'ACI WORLDWIDE INC' },
    { value: 'ACTUA CORP', label: 'ACTUA CORP' },
    { value: 'ADEXA INC', label: 'ADEXA INC' },
    { value: 'ADOBE INC', label: 'ADOBE INC' },
    { value: 'ADVANCED VOICE RECOGNITION', label: 'ADVANCED VOICE RECOGNITION' },
    { value: 'ADVANT-E CORP', label: 'ADVANT-E CORP' },
    { value: 'ADVANTEGO CORP', label: 'ADVANTEGO CORP' },
    { value: 'AGILYSYS INC', label: 'AGILYSYS INC' },
    { value: 'ALARM.COM HOLDINGS INC', label: 'ALARM.COM HOLDINGS INC' },
    { value: 'ALLDIGITAL HOLDINGS INC', label: 'ALLDIGITAL HOLDINGS INC' },
    { value: 'ALTAIR ENGINEERING INC', label: 'ALTAIR ENGINEERING INC' },
    { value: 'ALTERYX INC', label: 'ALTERYX INC' },
    { value: 'AMERICAN SECURITY RES CORP', label: 'AMERICAN SECURITY RES CORP' },
    { value: 'AMERICAN SOFTWARE  -CL A', label: 'AMERICAN SOFTWARE  -CL A' },
    { value: 'ANAPLAN INC', label: 'ANAPLAN INC' },
    { value: 'ANSYS INC', label: 'ANSYS INC' },
    { value: 'APPFOLIO INC', label: 'APPFOLIO INC' },
    { value: 'APPIAN CORP', label: 'APPIAN CORP' },
    { value: 'APPLIED VISUAL SCIENCES INC', label: 'APPLIED VISUAL SCIENCES INC' },
    { value: 'APT SYSTEMS INC', label: 'APT SYSTEMS INC' },
    { value: 'ASANA INC', label: 'ASANA INC' },
    { value: 'ASPEN TECHNOLOGY INC', label: 'ASPEN TECHNOLOGY INC' },
    { value: 'ASURE SOFTWARE INC', label: 'ASURE SOFTWARE INC' },
    { value: 'AUDIOEYE INC', label: 'AUDIOEYE INC' },
    { value: 'AUTODESK INC', label: 'AUTODESK INC' },
    { value: 'AUTOMATIC DATA PROCESSING', label: 'AUTOMATIC DATA PROCESSING' },
    { value: 'AVALARA INC', label: 'AVALARA INC' },
    { value: 'AVAYA HLDGS CORP', label: 'AVAYA HLDGS CORP' },
    { value: 'AWARE INC', label: 'AWARE INC' },
    { value: 'BARRACUDA NETWORKS INC', label: 'BARRACUDA NETWORKS INC' },
    { value: 'BENEFITFOCUS INC', label: 'BENEFITFOCUS INC' },
    { value: 'BENTLEY SYSTEMS INC', label: 'BENTLEY SYSTEMS INC' },
    { value: 'BIGCOMMERCE HOLDIN INC', label: 'BIGCOMMERCE HOLDIN INC' },
    { value: 'BILL.COM HOLDINGS INC', label: 'BILL.COM HOLDINGS INC' },
    { value: 'BIO-KEY INTERNATIONAL INC', label: 'BIO-KEY INTERNATIONAL INC' },
    { value: 'BLACK BOX CORP', label: 'BLACK BOX CORP' },
    { value: 'BLACKBAUD INC', label: 'BLACKBAUD INC' },
    { value: 'BLACKBOXSTOCKS INC', label: 'BLACKBOXSTOCKS INC' },
    { value: 'BLACKLINE INC', label: 'BLACKLINE INC' },
    { value: 'BLAQCLOUDS INC', label: 'BLAQCLOUDS INC' },
    { value: 'BOTTOMLINE TECHNOLOGIES INC', label: 'BOTTOMLINE TECHNOLOGIES INC' },
    { value: 'BOX INC', label: 'BOX INC' },
    { value: 'BOXLIGHT CORP', label: 'BOXLIGHT CORP' },
    { value: 'BRAVATEK SOLUTIONS INC', label: 'BRAVATEK SOLUTIONS INC' },
    { value: 'BRIDGELINE DIGITAL INC', label: 'BRIDGELINE DIGITAL INC' },
    { value: 'BRIDGEWAY NATIONAL CORP', label: 'BRIDGEWAY NATIONAL CORP' },
    { value: 'B-SCADA INC', label: 'B-SCADA INC' },
    { value: 'BSQUARE CORP', label: 'BSQUARE CORP' },
    { value: 'BUSYBOX.COM INC', label: 'BUSYBOX.COM INC' },
    { value: 'CADENCE DESIGN SYSTEMS INC', label: 'CADENCE DESIGN SYSTEMS INC' },
    { value: 'CDK GLOBAL INC', label: 'CDK GLOBAL INC' },
    { value: 'CERENCE INC', label: 'CERENCE INC' },
    { value: 'CERIDIAN CORP', label: 'CERIDIAN CORP' },
    { value: 'CERIDIAN HCM HOLDING', label: 'CERIDIAN HCM HOLDING' },
    { value: 'CHANGSHENG INTERNATIONAL GRO', label: 'CHANGSHENG INTERNATIONAL GRO' },
    { value: 'CHANNELADVISOR CORP', label: 'CHANNELADVISOR CORP' },
    { value: 'CHINA YANYUN YHU NTL ED GRP', label: 'CHINA YANYUN YHU NTL ED GRP' },
    { value: 'CICERO INC', label: 'CICERO INC' },
    { value: 'CIMETRIX INC', label: 'CIMETRIX INC' },
    { value: 'CIPHERLOC CORP', label: 'CIPHERLOC CORP' },
    { value: 'CITRIX SYSTEMS INC', label: 'CITRIX SYSTEMS INC' },
    { value: 'CLEANSPARK INC', label: 'CLEANSPARK INC' },
    { value: 'CLICKSTREAM CORP', label: 'CLICKSTREAM CORP' },
    { value: 'CLONE ALGO TECHNOLOGIES INC', label: 'CLONE ALGO TECHNOLOGIES INC' },
    { value: 'CLOUDERA INC', label: 'CLOUDERA INC' },
    { value: 'CLOUDFLARE INC', label: 'CLOUDFLARE INC' },
    { value: 'CLOUDWARD INC', label: 'CLOUDWARD INC' },
    { value: 'CODE REBEL CORP', label: 'CODE REBEL CORP' },
    { value: 'COM GUARD.COM INC', label: 'COM GUARD.COM INC' },
    { value: 'COMMVAULT SYSTEMS INC', label: 'COMMVAULT SYSTEMS INC' },
    { value: 'CORNERSTONE ONDEMAND INC', label: 'CORNERSTONE ONDEMAND INC' },
    { value: 'COUPA SOFTWARE INC', label: 'COUPA SOFTWARE INC' },
    { value: 'CROWDSTRIKE HOLDINGS INC', label: 'CROWDSTRIKE HOLDINGS INC' },
    { value: 'CYBERFORT SOFTWARE INC', label: 'CYBERFORT SOFTWARE INC' },
    { value: 'CYREN LTD', label: 'CYREN LTD' },
    { value: 'DATADOG INC', label: 'DATADOG INC' },
    { value: 'DATTO HOLDING CORP', label: 'DATTO HOLDING CORP' },
    { value: 'DEALERADVANCE INC', label: 'DEALERADVANCE INC' },
    { value: 'DIGILITI MONEY GROUP INC', label: 'DIGILITI MONEY GROUP INC' },
    { value: 'DIGIMARC CORP', label: 'DIGIMARC CORP' },
    { value: 'DIGITAL TURBINE INC', label: 'DIGITAL TURBINE INC' },
    { value: 'DOCUSIGN INC', label: 'DOCUSIGN INC' },
    { value: 'DOMO INC', label: 'DOMO INC' },
    { value: 'DROPBOX INC', label: 'DROPBOX INC' },
    { value: 'DUCK CREEK TECHNOL INC', label: 'DUCK CREEK TECHNOL INC' },
    { value: 'DYNATRACE INC', label: 'DYNATRACE INC' },
    { value: 'E2OPEN INC', label: 'E2OPEN INC' },
    { value: 'EBIX INC', label: 'EBIX INC' },
    { value: 'ECOARK HOLDINGS INC', label: 'ECOARK HOLDINGS INC' },
    { value: 'EGAIN CORP', label: 'EGAIN CORP' },
    { value: 'ELASTIC NETWORKS INC', label: 'ELASTIC NETWORKS INC' },
    { value: 'ELASTIC NV', label: 'ELASTIC NV' },
    { value: 'ELCOM INTERNATIONAL INC', label: 'ELCOM INTERNATIONAL INC' },
    { value: 'ENTERPRISE INFORMATICS INC', label: 'ENTERPRISE INFORMATICS INC' },
    { value: 'ENVESTNET INC', label: 'ENVESTNET INC' },
    { value: 'EVERBRIDGE INC', label: 'EVERBRIDGE INC' },
    { value: 'EVOLVING SYSTEMS INC', label: 'EVOLVING SYSTEMS INC' },
    { value: 'EZENIA INC', label: 'EZENIA INC' },
    { value: 'FAIR ISAAC CORP', label: 'FAIR ISAAC CORP' },
    { value: 'FALCONSTOR SOFTWARE INC', label: 'FALCONSTOR SOFTWARE INC' },
    { value: 'FANTASY ACES DAILY FANTASY', label: 'FANTASY ACES DAILY FANTASY' },
    { value: 'FASTLY INC', label: 'FASTLY INC' },
    { value: 'FIREEYE INC', label: 'FIREEYE INC' },
    { value: 'FIVE9 INC', label: 'FIVE9 INC' },
    { value: 'FLEXSHARES IBOXX 3-YR TAR FD', label: 'FLEXSHARES IBOXX 3-YR TAR FD' },
    { value: 'FLEXSHARES IBOXX 5-YR TAR FD', label: 'FLEXSHARES IBOXX 5-YR TAR FD' },
    { value: 'FORTINET INC', label: 'FORTINET INC' },
    { value: 'FRIENDFINDER NETWORKS INC', label: 'FRIENDFINDER NETWORKS INC' },
    { value: 'GIVEMEPOWER CORP', label: 'GIVEMEPOWER CORP' },
    { value: 'GRANDPARENTS.COM INC', label: 'GRANDPARENTS.COM INC' },
    { value: 'GREEN POLKADOT BOX INC', label: 'GREEN POLKADOT BOX INC' },
    { value: 'GSE SYSTEMS INC', label: 'GSE SYSTEMS INC' },
    { value: 'GTY TECHNOLOGY HOLDINGS', label: 'GTY TECHNOLOGY HOLDINGS' },
    { value: 'GUIDEWIRE SOFTWARE INC', label: 'GUIDEWIRE SOFTWARE INC' },
    { value: 'HOPTO INC', label: 'HOPTO INC' },
    { value: 'HRSOFT INC', label: 'HRSOFT INC' },
    { value: 'HUBSPOT INC', label: 'HUBSPOT INC' },
    { value: 'IBSG INTERNATIONAL INC', label: 'IBSG INTERNATIONAL INC' },
    { value: 'IDEANOMICS INC', label: 'IDEANOMICS INC' },
    { value: 'IMAGEWARE SYSTEMS INC', label: 'IMAGEWARE SYSTEMS INC' },
    { value: 'INFORMATION RESOURCES INC', label: 'INFORMATION RESOURCES INC' },
    { value: 'INTEGRATED BUSINESS SYS &SVC', label: 'INTEGRATED BUSINESS SYS &SVC' },
    { value: 'INTELLIGENT SYSTEM CORP', label: 'INTELLIGENT SYSTEM CORP' },
    { value: 'INTELLINETICS INC', label: 'INTELLINETICS INC' },
    { value: 'INTERMAP TECHNOLOGIES CORP', label: 'INTERMAP TECHNOLOGIES CORP' },
    { value: 'INTERNATIONAL LEADERS CAP CO', label: 'INTERNATIONAL LEADERS CAP CO' },
    { value: 'INTRUSION INC', label: 'INTRUSION INC' },
    { value: 'INTUIT INC', label: 'INTUIT INC' },
    { value: 'INUVO INC', label: 'INUVO INC' },
    { value: 'IRONCLAD ENCRYPTION CORP', label: 'IRONCLAD ENCRYPTION CORP' },
    { value: 'ISHARES IBOXX HIGH YLD CP BD', label: 'ISHARES IBOXX HIGH YLD CP BD' },
    { value: 'ISHARES IBOXX INVST GR CP BD', label: 'ISHARES IBOXX INVST GR CP BD' },
    { value: 'ISIGN SOLUTIONS INC', label: 'ISIGN SOLUTIONS INC' },
    { value: 'ISOCIALY INC', label: 'ISOCIALY INC' },
    { value: 'ISSUER DIRECT CORP', label: 'ISSUER DIRECT CORP' },
    { value: 'IVEDA SOLUTIONS INC', label: 'IVEDA SOLUTIONS INC' },
    { value: 'J2 GLOBAL INC', label: 'J2 GLOBAL INC' },
    { value: 'JACK IN THE BOX INC', label: 'JACK IN THE BOX INC' },
    { value: 'JAMF HOLDING CORP', label: 'JAMF HOLDING CORP' },
    { value: 'JDA SOFTWARE GROUP INC', label: 'JDA SOFTWARE GROUP INC' },
    { value: 'JFROG LTD', label: 'JFROG LTD' },
    { value: 'KIWIBOX COM INC', label: 'KIWIBOX COM INC' },
    { value: 'KRONOS INC', label: 'KRONOS INC' },
    { value: 'LAWSON SOFTWARE INC', label: 'LAWSON SOFTWARE INC' },
    { value: 'LEVELBLOX INC', label: 'LEVELBLOX INC' },
    { value: 'LIQUI-BOX CORP', label: 'LIQUI-BOX CORP' },
    { value: 'LIQUID HOLDINGS GROUP INC', label: 'LIQUID HOLDINGS GROUP INC' },
    { value: 'LIVE MICROSYSTEMS INC', label: 'LIVE MICROSYSTEMS INC' },
    { value: 'LIVEPERSON INC', label: 'LIVEPERSON INC' },
    { value: 'MAIL BOXES ETC', label: 'MAIL BOXES ETC' },
    { value: 'MANHATTAN ASSOCIATES INC', label: 'MANHATTAN ASSOCIATES INC' },
    { value: 'MARIN SOFTWARE INC', label: 'MARIN SOFTWARE INC' },
    { value: 'MAX SOUND CORP', label: 'MAX SOUND CORP' },
    { value: 'MEDALLIA INC', label: 'MEDALLIA INC' },
    { value: 'MEDALLIANCE INC', label: 'MEDALLIANCE INC' },
    { value: 'MEDIATECHNICS CORP', label: 'MEDIATECHNICS CORP' },
    { value: 'MGT CAPITAL INVESTMENTS INC', label: 'MGT CAPITAL INVESTMENTS INC' },
    { value: 'MICROSOFT CORP', label: 'MICROSOFT CORP' },
    { value: 'MICROSTRATEGY INC', label: 'MICROSTRATEGY INC' },
    { value: 'MITEK SYSTEMS INC', label: 'MITEK SYSTEMS INC' },
    { value: 'MIX TELEMATICS LTD', label: 'MIX TELEMATICS LTD' },
    { value: 'MOBILEIRON INC', label: 'MOBILEIRON INC' },
    { value: 'MODEL N INC', label: 'MODEL N INC' },
    { value: 'MONGODB INC', label: 'MONGODB INC' },
    { value: 'MONSTER ARTS', label: 'MONSTER ARTS' },
    { value: 'NCINO INC', label: 'NCINO INC' },
    { value: 'NEOMEDIA TECHNOLOGIES INC', label: 'NEOMEDIA TECHNOLOGIES INC' },
    { value: 'NETSOL TECHNOLOGIES INC', label: 'NETSOL TECHNOLOGIES INC' },
    { value: 'NEW RELIC INC', label: 'NEW RELIC INC' },
    { value: 'NORTONLIFELOCK INC', label: 'NORTONLIFELOCK INC' },
    { value: 'NOTIFY TECHNOLOGY CORP', label: 'NOTIFY TECHNOLOGY CORP' },
    { value: 'NUANCE COMMUNICATIONS INC', label: 'NUANCE COMMUNICATIONS INC' },
    { value: 'NUTANIX INC', label: 'NUTANIX INC' },
    { value: 'OBLONG INC', label: 'OBLONG INC' },
    { value: 'OKTA INC', label: 'OKTA INC' },
    { value: 'OMTOOL LTD', label: 'OMTOOL LTD' },
    { value: 'ONESPAN INC', label: 'ONESPAN INC' },
    { value: 'ORACLE CORP', label: 'ORACLE CORP' },
    { value: 'PAGERDUTY INC', label: 'PAGERDUTY INC' },
    { value: 'PAID INC', label: 'PAID INC' },
    { value: 'PALANTIR TECHNOLOG INC', label: 'PALANTIR TECHNOLOG INC' },
    { value: 'PALO ALTO NETWORKS INC', label: 'PALO ALTO NETWORKS INC' },
    { value: 'PARETEUM CORP', label: 'PARETEUM CORP' },
    { value: 'PARK CITY GROUP INC', label: 'PARK CITY GROUP INC' },
    { value: 'PAYBOX CORP', label: 'PAYBOX CORP' },
    { value: 'PAYCHEX INC', label: 'PAYCHEX INC' },
    { value: 'PAYCOM SOFTWARE INC', label: 'PAYCOM SOFTWARE INC' },
    { value: 'PAYLOCITY HOLDING CORP', label: 'PAYLOCITY HOLDING CORP' },
    { value: 'PEGASYSTEMS INC', label: 'PEGASYSTEMS INC' },
    { value: 'PHUNWARE INC', label: 'PHUNWARE INC' },
    { value: 'PING IDENTITY HOLDING CORP', label: 'PING IDENTITY HOLDING CORP' },
    { value: 'PLURALSIGHT INC', label: 'PLURALSIGHT INC' },
    { value: 'PRIMAL SOLUTIONS INC', label: 'PRIMAL SOLUTIONS INC' },
    { value: 'PROGRESS SOFTWARE CORP', label: 'PROGRESS SOFTWARE CORP' },
    { value: 'PROOFPOINT INC', label: 'PROOFPOINT INC' },
    { value: 'PROS HOLDINGS INC', label: 'PROS HOLDINGS INC' },
    { value: 'PTC INC', label: 'PTC INC' },
    { value: 'PULSE EVOLUTION CORP', label: 'PULSE EVOLUTION CORP' },
    { value: 'Q2 HOLDINGS INC', label: 'Q2 HOLDINGS INC' },
    { value: 'QAD INC', label: 'QAD INC' },
    { value: 'QUALYS INC', label: 'QUALYS INC' },
    { value: 'QUANTGATE SYSTEMS INC', label: 'QUANTGATE SYSTEMS INC' },
    { value: 'QUMU CORP', label: 'QUMU CORP' },
    { value: 'RAADR INC', label: 'RAADR INC' },
    { value: 'RAND WORLDWIDE INC', label: 'RAND WORLDWIDE INC' },
    { value: 'RAPID7 INC', label: 'RAPID7 INC' },
    { value: 'REALNETWORKS INC', label: 'REALNETWORKS INC' },
    { value: 'REALPAGE INC', label: 'REALPAGE INC' },
    { value: 'RIGHTSCORP INC', label: 'RIGHTSCORP INC' },
    { value: 'RINGCENTRAL INC', label: 'RINGCENTRAL INC' },
    { value: 'RIOT BLOCKCHAIN INC', label: 'RIOT BLOCKCHAIN INC' },
    { value: 'ROCKETFUEL BLOCKCHAIN INC', label: 'ROCKETFUEL BLOCKCHAIN INC' },
    { value: 'RORINE INTL HOLDING CORP', label: 'RORINE INTL HOLDING CORP' },
    { value: 'ROSETTA STONE INC', label: 'ROSETTA STONE INC' },
    { value: 'SAILPOINT TECHNO HLDG', label: 'SAILPOINT TECHNO HLDG' },
    { value: 'SALESFORCE.COM INC', label: 'SALESFORCE.COM INC' },
    { value: 'SCIENT INC', label: 'SCIENT INC' },
    { value: 'SEACHANGE INTERNATIONAL INC', label: 'SEACHANGE INTERNATIONAL INC' },
    { value: 'SECUREWORKS CORP', label: 'SECUREWORKS CORP' },
    { value: 'SERVICENOW INC', label: 'SERVICENOW INC' },
    { value: 'SHARPSPRING INC', label: 'SHARPSPRING INC' },
    { value: 'SHOTSPOTTER INC', label: 'SHOTSPOTTER INC' },
    { value: 'SIMTROL INC', label: 'SIMTROL INC' },
    { value: 'SITO MOBILE LTD', label: 'SITO MOBILE LTD' },
    { value: 'SKYBOX INTL INC', label: 'SKYBOX INTL INC' },
    { value: 'SLACK TECHNOLOGIES INC', label: 'SLACK TECHNOLOGIES INC' },
    { value: 'SMARTMETRIC INC', label: 'SMARTMETRIC INC' },
    { value: 'SMARTSHEET INC', label: 'SMARTSHEET INC' },
    { value: 'SMITH MICRO SOFTWARE INC', label: 'SMITH MICRO SOFTWARE INC' },
    { value: 'SNOWFLAKE INC', label: 'SNOWFLAKE INC' },
    { value: 'SOFTECH INC', label: 'SOFTECH INC' },
    { value: 'SOLARWINDS CORP', label: 'SOLARWINDS CORP' },
    { value: 'SONIC FOUNDRY INC', label: 'SONIC FOUNDRY INC' },
    { value: 'SPLUNK INC', label: 'SPLUNK INC' },
    { value: 'SPROUT SOCIAL INC', label: 'SPROUT SOCIAL INC' },
    { value: 'SPS COMMERCE INC', label: 'SPS COMMERCE INC' },
    { value: 'SS&C TECHNOLOGIES HLDGS INC', label: 'SS&C TECHNOLOGIES HLDGS INC' },
    { value: 'SSI INVESTMENTS II LTD', label: 'SSI INVESTMENTS II LTD' },
    { value: 'SUMO LOGIC INC', label: 'SUMO LOGIC INC' },
    { value: 'SVMK INC', label: 'SVMK INC' },
    { value: 'SYNACOR INC', label: 'SYNACOR INC' },
    { value: 'SYNCHRONOSS TECHNOLOGIES', label: 'SYNCHRONOSS TECHNOLOGIES' },
    { value: 'SYNOPSYS INC', label: 'SYNOPSYS INC' },
    { value: 'TAUTACHROME INC', label: 'TAUTACHROME INC' },
    { value: 'TELENAV INC', label: 'TELENAV INC' },
    { value: 'TENABLE HOLDINGS INC', label: 'TENABLE HOLDINGS INC' },
    { value: 'TERADATA CORP', label: 'TERADATA CORP' },
    { value: 'THEGLOBE.COM INC', label: 'THEGLOBE.COM INC' },
    { value: 'TIBCO SOFTWARE INC', label: 'TIBCO SOFTWARE INC' },
    { value: 'TINTRI INC', label: 'TINTRI INC' },
    { value: 'TMM INC', label: 'TMM INC' },
    { value: 'TRADE DESK INC', label: 'TRADE DESK INC' },
    { value: 'TWILIO INC', label: 'TWILIO INC' },
    { value: 'TYLER TECHNOLOGIES INC', label: 'TYLER TECHNOLOGIES INC' },
    { value: 'ULTIMATE SOFTWARE GROUP INC', label: 'ULTIMATE SOFTWARE GROUP INC' },
    { value: 'UNITRONIX CORP', label: 'UNITRONIX CORP' },
    { value: 'UNITY SOFTWARE INC', label: 'UNITY SOFTWARE INC' },
    { value: 'UPLAND SOFTWARE INC', label: 'UPLAND SOFTWARE INC' },
    { value: 'VANCORD CAPITAL INC', label: 'VANCORD CAPITAL INC' },
    { value: 'VARONIS SYSTEMS INC', label: 'VARONIS SYSTEMS INC' },
    { value: 'VDO-PH INTERNATIONAL INC', label: 'VDO-PH INTERNATIONAL INC' },
    { value: 'VEEVA SYSTEMS INC', label: 'VEEVA SYSTEMS INC' },
    { value: 'VERB TECHNOLOGY CO INC', label: 'VERB TECHNOLOGY CO INC' },
    { value: 'VERINT SYSTEMS INC', label: 'VERINT SYSTEMS INC' },
    { value: 'VERITONE INC', label: 'VERITONE INC' },
    { value: 'VERTEX INC', label: 'VERTEX INC' },
    { value: 'VERTICAL COMPUTER SYS INC', label: 'VERTICAL COMPUTER SYS INC' },
    { value: 'VIRNETX HOLDING CORP', label: 'VIRNETX HOLDING CORP' },
    { value: 'VIVA ENTERTAINMENT GROUP INC', label: 'VIVA ENTERTAINMENT GROUP INC' },
    { value: 'VMWARE INC -CL A', label: 'VMWARE INC -CL A' },
    { value: 'VOYAGER DIGITAL LTD', label: 'VOYAGER DIGITAL LTD' },
    { value: 'VUBOTICS INC', label: 'VUBOTICS INC' },
    { value: 'WOD RETAIL SOLUTIONS', label: 'WOD RETAIL SOLUTIONS' },
    { value: 'WORKDAY INC', label: 'WORKDAY INC' },
    { value: 'WORKIVA INC', label: 'WORKIVA INC' },
    { value: 'XCELMOBILITY INC', label: 'XCELMOBILITY INC' },
    { value: 'XPERI HOLDING CORP', label: 'XPERI HOLDING CORP' },
    { value: 'YAPPN CORP', label: 'YAPPN CORP' },
    { value: 'YEXT INC', label: 'YEXT INC' },
    { value: 'ZENDESK INC', label: 'ZENDESK INC' },
    { value: 'ZIX CORP', label: 'ZIX CORP' },
    { value: 'ZOOM TELEPHONICS INC', label: 'ZOOM TELEPHONICS INC' },
    { value: 'ZOOM VIDEO COMUNICATIONS INC', label: 'ZOOM VIDEO COMUNICATIONS INC' },
    { value: 'ZOOMAWAY TRAVEL INC', label: 'ZOOMAWAY TRAVEL INC' },
    { value: 'ZOOMINFO TECHNOLOGIES', label: 'ZOOMINFO TECHNOLOGIES' },
    { value: 'ZSCALER INC', label: 'ZSCALER INC' },
    { value: 'ZUORA INC', label: 'ZUORA INC' }
]
